"""Initialising Models

Revision ID: 6f215625f963
Revises:
Create Date: 2024-05-17 16:51:38.563910

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6f215625f963"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("disabled", sa.Boolean(), nullable=True),
        sa.Column("scope", sa.Enum("admin", "edit", name="scopes"), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("username"),
    )
    op.create_index(op.f("ix_admins_username"), "admins", ["username"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("txid", sa.String(), nullable=True),
        sa.Column("amount", sa.FLOAT(), nullable=True),
        sa.Column("payment_method", sa.String(), nullable=True),
        sa.Column("product", sa.String(), nullable=True),
        sa.Column("email_id", sa.String(), nullable=True),
        sa.Column("contact_no", sa.String(), nullable=True),
        sa.Column("subscription", sa.Integer(), nullable=True),
        sa.Column("order_date", sa.DateTime(), nullable=True),
        sa.Column("Start_Date", sa.DATE(), nullable=True),
        sa.Column("End_Date", sa.DATE(), nullable=True),
        sa.Column("License_Key", sa.String(), nullable=True),
        sa.Column("License_Activated", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("License_Key"),
        sa.UniqueConstraint("txid"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_admins_username"), table_name="admins")
    op.drop_table("admins")
    # ### end Alembic commands ###
